name             'pythonapp-test'
maintainer       'Rackspace'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures pythonapp-test'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends 'pythonapp'
depends 'nginx'
depends 'apache'
