---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: centos-6.5
    run_list:
      - recipe[yum-epel]
  - name: centos-7.0
    run_list:
      - recipe[yum-epel]

suites:
  - name: nginx
    run_list:
      - recipe[pythonapp-test::nginx]
    attributes:
  - name: apache
    run_list:
      - recipe[pythonapp-test::apache]
    attributes:
